# Generated by Django 3.0.8 on 2020-10-05 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200924_1610'),
        ('checkout', '0002_order_member_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='combo_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Food_Combo'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='combo_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
