# Generated by Django 3.0.8 on 2020-10-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200924_1610'),
        ('checkout', '0003_auto_20201005_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='combo_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='ComboLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.OrderLineItem')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Food_Item')),
            ],
        ),
    ]
