# Generated by Django 3.0.8 on 2020-10-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200924_1610'),
        ('checkout', '0004_auto_20201005_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combolineitem',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combocontents', to='checkout.OrderLineItem'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Food_Item'),
        ),
    ]
