# Generated by Django 3.0.8 on 2020-10-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20201005_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
