# Generated by Django 3.0.8 on 2020-10-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='for_collection',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
