# Generated by Django 3.0.8 on 2020-10-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_order_for_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='for_collection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
