# Generated by Django 3.0.8 on 2020-11-09 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20201101_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_instructions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=80, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
