# Generated by Django 3.0.8 on 2020-09-22 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('saved_mobile_number', models.CharField(blank=True, max_length=13, null=True)),
                ('saved_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('saved_address_line1', models.CharField(blank=True, max_length=80, null=True)),
                ('saved_address_line2', models.CharField(blank=True, max_length=80, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
