# Generated by Django 3.0.8 on 2020-10-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='saved_delivery_instructions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
