# Generated by Django 3.0.8 on 2020-10-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_area', '0002_memberprofile_saved_delivery_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='reward_status',
            field=models.IntegerField(default=0),
        ),
    ]
