# Generated by Django 3.0.8 on 2020-11-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_area', '0003_memberprofile_reward_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='saved_delivery_instructions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='saved_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='saved_postcode',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
