# Generated by Django 3.0.8 on 2020-11-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_area', '0004_auto_20201109_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='saved_email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
    ]
