# Generated by Django 3.0.8 on 2020-09-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_item',
            old_name='order_quantity',
            new_name='total_purchased',
        ),
    ]
