# Generated by Django 3.0.8 on 2020-11-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200924_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='total_purchased',
            field=models.IntegerField(default=0),
        ),
    ]
