# Generated by Django 3.0.8 on 2020-08-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200811_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('food_items', models.ManyToManyField(blank=True, null=True, to='menu.Food_Item')),
            ],
        ),
        migrations.AddField(
            model_name='food_item',
            name='food_combos',
            field=models.ManyToManyField(blank=True, null=True, to='menu.Food_Combo'),
        ),
    ]
