# Generated by Django 3.0.8 on 2020-08-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200813_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_combo',
            name='food_items',
        ),
        migrations.AlterField(
            model_name='food_item',
            name='food_combos',
            field=models.ManyToManyField(to='menu.Food_Combo'),
        ),
    ]
