# Generated by Django 3.0.8 on 2020-08-15 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200813_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Food_Combo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Food_Item')),
            ],
        ),
        migrations.AlterField(
            model_name='food_item',
            name='food_combos',
            field=models.ManyToManyField(related_name='food_items', through='menu.Combo_Item', to='menu.Food_Combo'),
        ),
    ]
