# Generated by Django 3.0.8 on 2020-09-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200813_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='food_combos',
            field=models.ManyToManyField(related_name='food_items', to='menu.Food_Combo'),
        ),
    ]
