# Generated by Django 3.0.8 on 2020-08-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200815_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='food_combos',
            field=models.ManyToManyField(related_name='food_items', to='menu.Food_Combo'),
        ),
        migrations.DeleteModel(
            name='Combo_Item',
        ),
    ]
